import { useState } from "react";
import { generateMealPlan, shareMealPlanEmail } from "../api";
import "../styles/dashboard.css";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function Nutrition() {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState([]);
  const [sendingEmail, setSendingEmail] = useState(false);

  // Load draft from storage or default
  const [formData, setFormData] = useState(() => {
    const saved = localStorage.getItem("nutrition_draft");
    return saved ? JSON.parse(saved) : {
      height: "",
      weight: "",
      goal: "Lose Weight",
      diet: "Vegetarian",
      allergies: ""
    };
  });

  // Auto-save draft
  useState(() => {
    // This needs to be in an effect, but since I am editing the state init, I will add the effect below.
  }, []); // Placeholder to avoid syntax error in replacer logic if I don't use effect imports properly.


  async function handleSubmit() {
    if (!formData.weight || !formData.height) {
      alert("Please enter both Weight and Height.");
      return;
    }
    if (formData.weight < 20 || formData.weight > 300) {
      alert("Please enter a valid weight between 20kg and 300kg.");
      return;
    }

    setLoading(true);
    try {
      const res = await generateMealPlan(formData);
      if (res.plan) {
        setPlan(res.plan);
        setStep(3);
      } else {
        alert(res.message || "Failed to generate plan.");
      }
    } catch (err) {
      alert("Error: " + err.message);
    } finally {
      setLoading(false);
    }
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(98, 0, 234);
    doc.text("Sai Aerobics - Personalized Meal Plan", 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Goal: ${formData.goal} | Diet: ${formData.diet}`, 14, 30);
    doc.text(`Weight: ${formData.weight}kg | Height: ${formData.height}`, 14, 36);

    // Prepare table data including calories
    const tableData = plan.map(day => [
      day.day,
      `${day.breakfast || '-'} (${day.calories_breakfast || ''})`,
      `${day.lunch || '-'} (${day.calories_lunch || ''})`,
      `${day.snack || '-'} (${day.calories_snack || ''})`,
      `${day.dinner || '-'} (${day.calories_dinner || ''})`
    ]);

    autoTable(doc, {
      startY: 45,
      head: [['Day', 'Breakfast', 'Lunch', 'Snack', 'Dinner']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [98, 0, 234] },
      styles: { fontSize: 8, cellPadding: 2 }
    });

    doc.save("SaiAerobics_MealPlan.pdf");
  };

  const handleShareEmail = async () => {
    setSendingEmail(true);
    // Construct simple HTML table for email
    let html = `<table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse; width:100%;">
        <tr style="background:#7c6cf2; color:white;">
            <th>Day</th><th>Breakfast</th><th>Lunch</th><th>Snack</th><th>Dinner</th>
        </tr>`;

    plan.forEach(p => {
      html += `<tr>
            <td><strong>${p.day}</strong></td>
            <td>${p.breakfast} <br><small>${p.calories_breakfast}</small></td>
            <td>${p.lunch} <br><small>${p.calories_lunch}</small></td>
            <td>${p.snack} <br><small>${p.calories_snack}</small></td>
            <td>${p.dinner} <br><small>${p.calories_dinner}</small></td>
          </tr>`;
    });
    html += `</table>`;

    try {
      const res = await shareMealPlanEmail(html, formData.goal);
      if (res.success) alert(res.message);
      else alert(res.error || "Failed");
    } catch (e) {
      alert("Email failed: " + e.message);
    } finally {
      setSendingEmail(false);
    }
  };

  return (
    <div className="dash">
      <header className="dash-header" style={{ justifyContent: 'center' }}>
        <h2>AI Nutritionist 🥗</h2>
      </header>

      <div style={{ background: "var(--card)", padding: "24px", borderRadius: "24px", boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
        {/* Form Step */}
        {step === 1 && (
          <div className="fade-in">
            <p className="modal-desc">Get a personalized 7-day Indian meal plan generated by AI.</p>

            <div className="form-group">
              <label>Current Weight (kg) <span style={{ color: 'red' }}>*</span></label>
              <input
                type="number"
                min="20"
                max="300"
                required
                className="styled-input"
                value={formData.weight}
                onChange={e => setFormData({ ...formData, weight: e.target.value })}
                placeholder="e.g. 65"
              />
            </div>
            <div className="form-group">
              <label>Height <span style={{ color: 'red' }}>*</span></label>
              <input
                type="text"
                required
                className="styled-input"
                value={formData.height}
                onChange={e => setFormData({ ...formData, height: e.target.value })}
                placeholder="e.g. 5'5 or 165cm"
              />
            </div>

            <div className="form-group">
              <label>Goal</label>
              <select className="styled-input" value={formData.goal} onChange={e => setFormData({ ...formData, goal: e.target.value })}>
                <option>Lose Weight</option><option>Maintain Weight</option><option>Gain Muscle</option>
              </select>
            </div>

            <div className="form-group">
              <label>Diet Type</label>
              <select className="styled-input" value={formData.diet} onChange={e => setFormData({ ...formData, diet: e.target.value })}>
                <option>Vegetarian</option><option>Eggetarian</option><option>Non-Vegetarian</option><option>Vegan</option>
              </select>
            </div>

            <div className="form-group"><label>Allergies (Optional)</label><input type="text" className="styled-input" value={formData.allergies} onChange={e => setFormData({ ...formData, allergies: e.target.value })} placeholder="e.g. Peanuts, Dairy" /></div>

            <button className="big-log-btn" onClick={handleSubmit} style={{ marginTop: "20px", background: "var(--primary-purple)", color: "white" }} disabled={loading}>
              {loading ? "Generating Plan..." : "Generate Meal Plan ✨"}
            </button>
          </div>
        )}

        {/* Result Step */}
        {step === 3 && (
          <div className="fade-in">
            <h3 style={{ marginTop: 0, color: "var(--success)" }}>Plan Ready! ✅</h3>

            <div style={{ display: "flex", gap: "10px", marginBottom: "20px", flexWrap: "wrap" }}>
              <button onClick={handleDownloadPDF} style={{ flex: 1, padding: "10px", borderRadius: "12px", border: "none", background: "#ef4444", color: "white", cursor: "pointer", fontWeight: "600" }}>Download PDF 📥</button>
              <button onClick={handleShareEmail} disabled={sendingEmail} style={{ flex: 1, padding: "10px", borderRadius: "12px", border: "1px solid var(--primary-purple)", background: "rgba(98, 0, 234, 0.1)", color: "var(--primary-purple)", cursor: "pointer", fontWeight: "600" }}>
                {sendingEmail ? "Sending..." : "Email to Me 📧"}
              </button>
            </div>

            <div className="meal-grid" style={{ display: "grid", gap: "15px", maxHeight: "500px", overflowY: "auto" }}>
              {Array.isArray(plan) && plan.map((day, i) => (
                <div key={i} style={{ background: "var(--bg)", padding: "15px", borderRadius: "12px", borderLeft: "4px solid var(--primary-purple)" }}>
                  <strong style={{ display: "block", fontSize: "1.1rem", marginBottom: "8px", color: "var(--primary-purple)" }}>{day.day}</strong>
                  <div style={{ display: "grid", gridTemplateColumns: "auto 1fr auto", gap: "8px", fontSize: "0.9rem", alignItems: "center" }}>
                    <span style={{ color: "var(--text-muted)" }}>🍳 Breakfast:</span> <span>{day.breakfast}</span> <span className="cal-badge">{day.calories_breakfast}</span>
                    <span style={{ color: "var(--text-muted)" }}>🍛 Lunch:</span> <span>{day.lunch}</span> <span className="cal-badge">{day.calories_lunch}</span>
                    <span style={{ color: "var(--text-muted)" }}>🥨 Snack:</span> <span>{day.snack}</span> <span className="cal-badge">{day.calories_snack}</span>
                    <span style={{ color: "var(--text-muted)" }}>🍲 Dinner:</span> <span>{day.dinner}</span> <span className="cal-badge">{day.calories_dinner}</span>
                  </div>
                </div>
              ))}
            </div>

            <button className="primary-btn" onClick={() => setStep(1)} style={{ marginTop: "20px", width: "100%", padding: "12px", background: "var(--text-main)", color: "var(--bg)", border: "none", borderRadius: "12px", fontWeight: "600", cursor: "pointer" }}>Create New Plan</button>
          </div>
        )}
      </div>
    </div>
  );
}
